on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Sync files to blog
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_branch: main
          src_path: /.
          dst_path: /_posts/
          dst_owner: LanglandsLearningGroup
          dst_repo_name: LanglandsLearningGroup.github.io
          file_filter: '*.md'
